[package]
name = "unisonht"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
log = "0.4.14"
simple_logger = "1.13.0"
ureq = "2.2.0"
