modes:
  off:
    enter:
      actions:
        - type: http
          url: http://localhost:8081/api/v1/power/tv/off
        - type: http
          url: http://localhost:8081/api/v1/power/receiver/off

  tv:
    enter:
      actions:
        - type: http
          url: http://localhost:8081/api/v1/power/tv/on
        - type: chain
          actions:
            - type: http
              url: http://localhost:8081/api/v1/power/receiver/on
            - type: http
              url: http://localhost:8081/api/v1/transmit/receiver/input-tv

buttonMapping:
  volumeUp:
    actions:
      - type: http
        url: http://localhost:8081/api/v1/transmit/receiver/volume-up
  volumeDown:
    actions:
      - type: http
        url: http://localhost:8081/api/v1/transmit/receiver/volume-down
