#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DEST=$1

ssh ${DEST} mkdir -p unisonht
rsync -r --exclude node_modules --exclude target ${DIR}/* ${DEST}:unisonht
#ssh ${DEST} '. ~/.nvm/nvm.sh && cd ~/unisonht && npm install'
ssh ${DEST} '. ~/.nvm/nvm.sh && cd ~/unisonht && npm run build'
